ingress:
  # -- Setting that allows Longhorn to generate ingress records for the Longhorn UI service.
  enabled: true
  host: longhornui.services.labk3s.perihelion.lan
  tls: true
  tlsSecret: longhorn.local-tls
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: my-ca-issuer
    # configuring the certificate
    cert-manager.io/common-name: "longhornui.services.labk3s.perihelion.lan/"
    cert-manager.io/subject-organizations: "Home Lab"
    cert-manager.io/subject-organizationalunits: "Longhorn on K3s Lab"
    cert-manager.io/duration: 720h
    cert-manager.io/renew-before: 240h
    cert-manager.io/usages: "digital signature,key agreement,server auth, client auth"

# metrics:
#   serviceMonitor:
#     # -- Setting that allows the creation of a Prometheus ServiceMonitor resource for Longhorn Manager components.
#     enabled: true
