hostname: rancherui.services.labk3s.perihelion.lan
ingress:
  enabled: true
  extraAnnotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: my-ca-issuer
    # configuring the certificate
    cert-manager.io/common-name: "rancherui.services.labk3s.perihelion.lan/"
    cert-manager.io/subject-organizations: "Home Lab"
    cert-manager.io/subject-organizationalunits: "Rancher on K3s Lab"
    cert-manager.io/duration: 720h
    cert-manager.io/renew-before: 240h
    cert-manager.io/usages: "digital signature,key agreement,server auth, client auth"
  tls: 
    source: secret
