type: postgresql
mode: standalone
version:
  postgresql: "17"
cluster:
  instances: 1
  storage:
    size: 1Gi
# Define a backup schedule. Pick a time when the machine is likely running.
#
# Local backups not supported?????
#
# backups:
#   enabled: true
#   scheduledBackups:
#     - name: daily-backup
#       schedule: "0 0 0 * * *" # Daily at midnight
#       backupOwnerReference: self
