type: postgresql
mode: standalone
version:
  postgresql: "17"
cluster:
  instances: 1
  storage:
    size: 1Gi
  initdb:
    database: k3slab
    owner: "k3slab" # Defaults to the database name
    # secret:
    #   name: "k3slab-nha" # Name of the secret containing the initial credentials for the owner of the user database. If empty a new secret will be created from scratch
    options: []
    encoding: UTF8
    postInitSQL:
      # - CREATE EXTENSION IF NOT EXISTS vector;
      - CREATE EXTENSION IF NOT EXISTS pgcrypto;
    postInitApplicationSQL: []
    postInitTemplateSQL: []


# Define a backup schedule. Pick a time when the machine is likely running.
#
# Local backups not supported?????
#
# backups:
#   enabled: true
#   scheduledBackups:
#     - name: daily-backup
#       schedule: "0 0 0 * * *" # Daily at midnight
#       backupOwnerReference: self
