# https://github.com/cert-manager/cert-manager/issues/5851#issuecomment-2413359368
# I encountered the same issue and resolved it by extending the duration of the self-signed CA, ensuring that the renewBefore period is longer than the duration of the issued certificate. This guarantees that the signed certificate always has a valid (non-expired) CA certificate.
# For example:
# Self-signed CA: duration of 6 months, with renewBefore set to 3 months
# Issued Certificate: duration of 3 months, with renewBefore set to 1 day

# Bootstrapping CA issuers
# https://cert-manager.io/docs/configuration/selfsigned/#bootstrapping-ca-issuers

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: my-selfsigned-ca
  # duration 87660h is 10 years, see see cert-manager.crds.yaml line 113, see https://cert-manager.io/docs/usage/certificate/#reissuance-triggered-by-expiry-renewal
  duration: 87660h
  # renewBefore see cert-manager.crds.yaml line 804
  renewBefore: 1440h
  # why subject is needed see:  https://cert-manager.io/docs/configuration/selfsigned/#certificate-validity
  subject: 
    organizations: 
      - "Home Lab"
    organizationalUnits:
      - "K3s Lab"
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-ca-issuer
spec:
  ca:
    secretName: root-secret